#!/usr/bin/env bash

source ./utils.sh

install_pacman fzf
install_apt fzf

curl -sS https://starship.rs/install.sh | sh

install_pacman exa
install_apt exa

install_pacman bat
install_apt bat


install_pacman jq
install_apt jq

install_pacman parallel
install_apt parallel

